function [params, species] = nfkbInitialize()
% This file is automatically generated by updateModel.m from the NFkB whole-cell spreadsheet
% Model URL: multi-stimulus NFkB.xlsx

rng('shuffle');
pert = 0.25; % ### 25% Perturbation for each parameters
% PARAMETERS
params(1,1) = 1; % induced IKK activation (general)
mu11 = log((params(1,1)^2)/sqrt(((pert*params(1,1))^2)+(params(1,1)^2)));
sigma11 = sqrt(log(((pert*params(1,1))^2)/(params(1,1)^2)+1));
params(1,1) = lognrnd(mu11,sigma11);
%
params(2,1) = 2e-05; % basal IKK activation
mu21 = log((params(2,1)^2)/sqrt(((pert*params(2,1))^2)+(params(2,1)^2)));
sigma21 = sqrt(log(((pert*params(2,1))^2)/(params(2,1)^2)+1));
params(2,1) = lognrnd(mu21,sigma21);
%
params(3,1) = 2; % IKK inhibition (IKK cycling)
mu31 = log((params(3,1)^2)/sqrt(((pert*params(3,1))^2)+(params(3,1)^2)));
sigma31 = sqrt(log(((pert*params(3,1))^2)/(params(3,1)^2)+1));
params(3,1) = lognrnd(mu31,sigma31);
% 
params(4,1) = 18; % IKK renewal (IKK cycling)
mu41 = log((params(4,1)^2)/sqrt(((pert*params(4,1))^2)+(params(4,1)^2)));
sigma41 = sqrt(log(((pert*params(4,1))^2)/(params(4,1)^2)+1));
params(4,1) = lognrnd(mu41,sigma41);
%
params(5,1) = 5e-07; % basal IkBa mRNA synthesis
mu51 = log((params(5,1)^2)/sqrt(((pert*params(5,1))^2)+(params(5,1)^2)));
sigma51 = sqrt(log(((pert*params(5,1))^2)/(params(5,1)^2)+1));
params(5,1) = lognrnd(mu51,sigma51);
%
params(6,1) = 6e-05; % induced IkBa mRNA synthesis
mu61 = log((params(6,1)^2)/sqrt(((pert*params(6,1))^2)+(params(6,1)^2)));
sigma61 = sqrt(log(((pert*params(6,1))^2)/(params(6,1)^2)+1));
params(6,1) = lognrnd(mu61,sigma61);
params(6,2) = 2.938; % Hill coefficient for mRNA syn
params(6,3) = 0.1775; % EC50 for mRNA syn
params(6,4) = 14; % mRNA transcription/processing/maturation delay
%
params(7,1) = 0.0577623; % IkBa mRNA degradation
mu71 = log((params(7,1)^2)/sqrt(((pert*params(7,1))^2)+(params(7,1)^2)));
sigma71 = sqrt(log(((pert*params(7,1))^2)/(params(7,1)^2)+1));
params(7,1) = lognrnd(mu71,sigma71);
%
params(8,1) = 30; % IkBa mRNA translation
mu81 = log((params(8,1)^2)/sqrt(((pert*params(8,1))^2)+(params(8,1)^2)));
sigma81 = sqrt(log(((pert*params(8,1))^2)/(params(8,1)^2)+1));
params(8,1) = lognrnd(mu81,sigma81);
params(8,2) = 1; % Translation/folding delay
%
params(9,1) = 0.0225; % nuclear import of IkBa
mu91 = log((params(9,1)^2)/sqrt(((pert*params(9,1))^2)+(params(9,1)^2)));
sigma91 = sqrt(log(((pert*params(9,1))^2)/(params(9,1)^2)+1));
params(9,1) = lognrnd(mu91,sigma91);
params(9,2) = 3.5; % Volume scale: cytoplasmic/nuclear volume
%
params(10,1) = 0.6; % nuclear import of NFkB
mu101 = log((params(10,1)^2)/sqrt(((pert*params(10,1))^2)+(params(10,1)^2)));
sigma101 = sqrt(log(((pert*params(10,1))^2)/(params(10,1)^2)+1));
params(10,1) = lognrnd(mu101,sigma101);
params(10,2) = 3.5; % Volume scale: cytoplasmic/nuclear volume
%
params(11,1) = 0.1575; % nuclear export of IkBa
mu111 = log((params(11,1)^2)/sqrt(((pert*params(11,1))^2)+(params(11,1)^2)));
sigma111 = sqrt(log(((pert*params(11,1))^2)/(params(11,1)^2)+1));
params(11,1) = lognrnd(mu111,sigma111);
params(11,2) = 0.285714; % Volume scale: nuclear/cytoplasmic volume
%
params(12,1) = 0.042; % nuclear export of NFkB
mu121 = log((params(12,1)^2)/sqrt(((pert*params(12,1))^2)+(params(12,1)^2)));
sigma121 = sqrt(log(((pert*params(12,1))^2)/(params(12,1)^2)+1));
params(12,1) = lognrnd(mu121,sigma121);
params(12,2) = 0.285714; % Volume scale: nuclear/cytoplasmic volume
%
params(13,1) = 0; % nuclear import of IkBa-NFkB
params(13,2) = 3.5; % Volume scale: cytoplasmic/nuclear volume
%
params(14,1) = 0.828; % nuclear export of IkBa-NFkB
mu141 = log((params(14,1)^2)/sqrt(((pert*params(14,1))^2)+(params(14,1)^2)));
sigma141 = sqrt(log(((pert*params(14,1))^2)/(params(14,1)^2)+1));
params(14,1) = lognrnd(mu141,sigma141);
params(14,2) = 0.285714; % Volume scale: cytoplasmic/nuclear volume
%
params(15,1) = 0.0770164; % degradation of IkBa
mu151 = log((params(15,1)^2)/sqrt(((pert*params(15,1))^2)+(params(15,1)^2)));
sigma151 = sqrt(log(((pert*params(15,1))^2)/(params(15,1)^2)+1));
params(15,1) = lognrnd(mu151,sigma151);
%
params(16,1) = 0.0770164; % degradation of IkBa (nuc)
mu161 = log((params(16,1)^2)/sqrt(((pert*params(16,1))^2)+(params(16,1)^2)));
sigma161 = sqrt(log(((pert*params(16,1))^2)/(params(16,1)^2)+1));
params(16,1) = lognrnd(mu161,sigma161);
%
params(17,1) = 200; % IkBa-NFkB association
mu171 = log((params(17,1)^2)/sqrt(((pert*params(17,1))^2)+(params(17,1)^2)));
sigma171 = sqrt(log(((pert*params(17,1))^2)/(params(17,1)^2)+1));
params(17,1) = lognrnd(mu171,sigma171);
%
params(18,1) = 200; % IkBa-NFkB association (nuc)
mu181 = log((params(18,1)^2)/sqrt(((pert*params(18,1))^2)+(params(18,1)^2)));
sigma181 = sqrt(log(((pert*params(18,1))^2)/(params(18,1)^2)+1));
params(18,1) = lognrnd(mu181,sigma181);
%
params(19,1) = 0.008; % IkBa-NFkB dissociation
mu191 = log((params(19,1)^2)/sqrt(((pert*params(19,1))^2)+(params(19,1)^2)));
sigma191 = sqrt(log(((pert*params(19,1))^2)/(params(19,1)^2)+1));
params(19,1) = lognrnd(mu191,sigma191);
%
params(20,1) = 0.008; % IkBa-NFkB dissociation (nuc)
mu201 = log((params(20,1)^2)/sqrt(((pert*params(20,1))^2)+(params(20,1)^2)));
sigma201 = sqrt(log(((pert*params(20,1))^2)/(params(20,1)^2)+1));
params(20,1) = lognrnd(mu201,sigma201);
%
params(21,1) = 190; % IKK-IkBa-NFkB association
mu211 = log((params(21,1)^2)/sqrt(((pert*params(21,1))^2)+(params(21,1)^2)));
sigma211 = sqrt(log(((pert*params(21,1))^2)/(params(21,1)^2)+1));
params(21,1) = lognrnd(mu211,sigma211);
%
params(22,1) = 190; % IKK-IkBa association
mu221 = log((params(22,1)^2)/sqrt(((pert*params(22,1))^2)+(params(22,1)^2)));
sigma221 = sqrt(log(((pert*params(22,1))^2)/(params(22,1)^2)+1));
params(22,1) = lognrnd(mu221,sigma221);
%
params(23,1) = 38; % IKK-IkBa-NFkB dissociation
mu231 = log((params(23,1)^2)/sqrt(((pert*params(23,1))^2)+(params(23,1)^2)));
sigma231 = sqrt(log(((pert*params(23,1))^2)/(params(23,1)^2)+1));
params(23,1) = lognrnd(mu231,sigma231);
%
params(24,1) = 38; % IKK-IkBa dissociation
mu241 = log((params(24,1)^2)/sqrt(((pert*params(24,1))^2)+(params(24,1)^2)));
sigma241 = sqrt(log(((pert*params(24,1))^2)/(params(24,1)^2)+1));
params(24,1) = lognrnd(mu241,sigma241);
%
params(25,1) = 2; % Phosphorylation/degradation of complexed IkBa
mu251 = log((params(25,1)^2)/sqrt(((pert*params(25,1))^2)+(params(25,1)^2)));
sigma251 = sqrt(log(((pert*params(25,1))^2)/(params(25,1)^2)+1));
params(25,1) = lognrnd(mu251,sigma251);
%
params(26,1) = 2; % Phosphorylation/degradation of IkBa
mu261 = log((params(26,1)^2)/sqrt(((pert*params(26,1))^2)+(params(26,1)^2)));
sigma261 = sqrt(log(((pert*params(26,1))^2)/(params(26,1)^2)+1));
params(26,1) = lognrnd(mu261,sigma261);
%
params(27,1) = 8.75; % CD14-LPS association
mu271 = log((params(27,1)^2)/sqrt(((pert*params(27,1))^2)+(params(27,1)^2)));
sigma271 = sqrt(log(((pert*params(27,1))^2)/(params(27,1)^2)+1));
params(27,1) = lognrnd(mu271,sigma271);
params(27,2) = 0.001; % Scale for external (media) vs. internal (cellular) volumes
%
params(28,1) = 0.07; % CD14-LPS dissociation
mu281 = log((params(28,1)^2)/sqrt(((pert*params(28,1))^2)+(params(28,1)^2)));
sigma281 = sqrt(log(((pert*params(28,1))^2)/(params(28,1)^2)+1));
params(28,1) = lognrnd(mu281,sigma281);
params(28,2) = 0.001; % Scale for external (media) vs. internal (cellular) volumes
%
params(29,1) = 0.00112; % CD14 synthesis
mu291 = log((params(29,1)^2)/sqrt(((pert*params(29,1))^2)+(params(29,1)^2)));
sigma291 = sqrt(log(((pert*params(29,1))^2)/(params(29,1)^2)+1));
params(29,1) = lognrnd(mu291,sigma291);
%
params(30,1) = 0.000878; % CD14 degradation
mu301 = log((params(30,1)^2)/sqrt(((pert*params(30,1))^2)+(params(30,1)^2)));
sigma301 = sqrt(log(((pert*params(30,1))^2)/(params(30,1)^2)+1));
params(30,1) = lognrnd(mu301,sigma301);
%
params(31,1) = 5.543; % Assocation of LPS and CD14 in plasma membrane
mu311 = log((params(31,1)^2)/sqrt(((pert*params(31,1))^2)+(params(31,1)^2)));
sigma311 = sqrt(log(((pert*params(31,1))^2)/(params(31,1)^2)+1));
params(31,1) = lognrnd(mu311,sigma311);
%
params(32,1) = 0.0277; % Disassociation of TLR4LPS in the plamsa membrane
mu321 = log((params(32,1)^2)/sqrt(((pert*params(32,1))^2)+(params(32,1)^2)));
sigma321 = sqrt(log(((pert*params(32,1))^2)/(params(32,1)^2)+1));
params(32,1) = lognrnd(mu321,sigma321);
%
params(33,1) = 5.543; % Assocation of LPS and CD14 in the endosome
mu331 = log((params(33,1)^2)/sqrt(((pert*params(33,1))^2)+(params(33,1)^2)));
sigma331 = sqrt(log(((pert*params(33,1))^2)/(params(33,1)^2)+1));
params(33,1) = lognrnd(mu331,sigma331);
%
params(34,1) = 0.0277; % Disassociation of TLR4LPS in the endosome
mu341 = log((params(34,1)^2)/sqrt(((pert*params(34,1))^2)+(params(34,1)^2)));
sigma341 = sqrt(log(((pert*params(34,1))^2)/(params(34,1)^2)+1));
params(34,1) = lognrnd(mu341,sigma341);
%
params(35,1) = 5.25e-05; % Synthesis rate of TLR4
mu351 = log((params(35,1)^2)/sqrt(((pert*params(35,1))^2)+(params(35,1)^2)));
sigma351 = sqrt(log(((pert*params(35,1))^2)/(params(35,1)^2)+1));
params(35,1) = lognrnd(mu351,sigma351);
%
params(36,1) = 0.065681; % Induced endocytosis of CD14
mu361 = log((params(36,1)^2)/sqrt(((pert*params(36,1))^2)+(params(36,1)^2)));
sigma361 = sqrt(log(((pert*params(36,1))^2)/(params(36,1)^2)+1));
params(36,1) = lognrnd(mu361,sigma361);
%
params(37,1) = 0.04; % Recycling of CD14
mu371 = log((params(37,1)^2)/sqrt(((pert*params(37,1))^2)+(params(37,1)^2)));
sigma371 = sqrt(log(((pert*params(37,1))^2)/(params(37,1)^2)+1));
params(37,1) = lognrnd(mu371,sigma371);
%
params(38,1) = 0.028028; % Constitutive endocytosis of TLR4
mu381 = log((params(38,1)^2)/sqrt(((pert*params(38,1))^2)+(params(38,1)^2)));
sigma381 = sqrt(log(((pert*params(38,1))^2)/(params(38,1)^2)+1));
params(38,1) = lognrnd(mu381,sigma381);
%
params(39,1) = 0.5; % Recycling of TLR4
mu391 = log((params(39,1)^2)/sqrt(((pert*params(39,1))^2)+(params(39,1)^2)));
sigma391 = sqrt(log(((pert*params(39,1))^2)/(params(39,1)^2)+1));
params(39,1) = lognrnd(mu391,sigma391);
%
params(40,1) = 0.065681; % Induced endocytosis of activated CD14-TLR4
mu401 = log((params(40,1)^2)/sqrt(((pert*params(40,1))^2)+(params(40,1)^2)));
sigma401 = sqrt(log(((pert*params(40,1))^2)/(params(40,1)^2)+1));
params(40,1) = lognrnd(mu401,sigma401);
%
params(41,1) = 0.04; % Recycling of CD14-TLR4
mu411 = log((params(41,1)^2)/sqrt(((pert*params(41,1))^2)+(params(41,1)^2)));
sigma411 = sqrt(log(((pert*params(41,1))^2)/(params(41,1)^2)+1));
params(41,1) = lognrnd(mu411,sigma411);
%
params(42,1) = 0.07; % Degradation of CD14-LPS
mu421 = log((params(42,1)^2)/sqrt(((pert*params(42,1))^2)+(params(42,1)^2)));
sigma421 = sqrt(log(((pert*params(42,1))^2)/(params(42,1)^2)+1));
params(42,1) = lognrnd(mu421,sigma421);
%
params(43,1) = 0.0653; % Degradation of TLR4
mu431 = log((params(43,1)^2)/sqrt(((pert*params(43,1))^2)+(params(43,1)^2)));
sigma431 = sqrt(log(((pert*params(43,1))^2)/(params(43,1)^2)+1));
params(43,1) = lognrnd(mu431,sigma431);
%
params(44,1) = 0.012; % Degradation of activated TLR4-LPS
mu441 = log((params(44,1)^2)/sqrt(((pert*params(44,1))^2)+(params(44,1)^2)));
sigma441 = sqrt(log(((pert*params(44,1))^2)/(params(44,1)^2)+1));
params(44,1) = lognrnd(mu441,sigma441);
%
params(45,1) = 150; % Activation of MyD88
mu451 = log((params(45,1)^2)/sqrt(((pert*params(45,1))^2)+(params(45,1)^2)));
sigma451 = sqrt(log(((pert*params(45,1))^2)/(params(45,1)^2)+1));
params(45,1) = lognrnd(mu451,sigma451);
params(45,2) = 3; % Hill coefficient for MyD88 activation
params(45,3) = 0.012448; % EC50 for MyD88 activation
%
params(46,1) = 2600; % Deactivation of MyD88
mu461 = log((params(46,1)^2)/sqrt(((pert*params(46,1))^2)+(params(46,1)^2)));
sigma461 = sqrt(log(((pert*params(46,1))^2)/(params(46,1)^2)+1));
params(46,1) = lognrnd(mu461,sigma461);
%
params(47,1) = 6; % Activation of TRIF
mu471 = log((params(47,1)^2)/sqrt(((pert*params(47,1))^2)+(params(47,1)^2)));
sigma471 = sqrt(log(((pert*params(47,1))^2)/(params(47,1)^2)+1));
params(47,1) = lognrnd(mu471,sigma471);
%
params(48,1) = 0.2; % Deactivation of TRIF
mu481 = log((params(48,1)^2)/sqrt(((pert*params(48,1))^2)+(params(48,1)^2)));
sigma481 = sqrt(log(((pert*params(48,1))^2)/(params(48,1)^2)+1));
params(48,1) = lognrnd(mu481,sigma481);
%
params(49,1) = 30; % Activation of TRAF6 by MyD88
mu491 = log((params(49,1)^2)/sqrt(((pert*params(49,1))^2)+(params(49,1)^2)));
sigma491 = sqrt(log(((pert*params(49,1))^2)/(params(49,1)^2)+1));
params(49,1) = lognrnd(mu491,sigma491);
%
params(50,1) = 0.4; % Activation of TRAF6 by TRIF
mu501 = log((params(50,1)^2)/sqrt(((pert*params(50,1))^2)+(params(50,1)^2)));
sigma501 = sqrt(log(((pert*params(50,1))^2)/(params(50,1)^2)+1));
params(50,1) = lognrnd(mu501,sigma501);
%
params(51,1) = 0.125; % Deactivation of TRAF6
mu511 = log((params(51,1)^2)/sqrt(((pert*params(51,1))^2)+(params(51,1)^2)));
sigma511 = sqrt(log(((pert*params(51,1))^2)/(params(51,1)^2)+1));
params(51,1) = lognrnd(mu511,sigma511);
%
params(52,1) = 0.105; % Activation of TAK1 by TRAF6
mu521 = log((params(52,1)^2)/sqrt(((pert*params(52,1))^2)+(params(52,1)^2)));
sigma521 = sqrt(log(((pert*params(52,1))^2)/(params(52,1)^2)+1));
params(52,1) = lognrnd(mu521,sigma521);
%
params(53,1) = 0.0116; % TNF degradation
mu531 = log((params(53,1)^2)/sqrt(((pert*params(53,1))^2)+(params(53,1)^2)));
sigma531 = sqrt(log(((pert*params(53,1))^2)/(params(53,1)^2)+1));
params(53,1) = lognrnd(mu531,sigma531);
%
params(54,1) = 8.224e-06; % TNFR synthesis
mu541 = log((params(54,1)^2)/sqrt(((pert*params(54,1))^2)+(params(54,1)^2)));
sigma541 = sqrt(log(((pert*params(54,1))^2)/(params(54,1)^2)+1));
params(54,1)= lognrnd(mu541,sigma541);
%
params(55,1) = 0.02384; % TNFR degradation
mu551 = log((params(55,1)^2)/sqrt(((pert*params(55,1))^2)+(params(55,1)^2)));
sigma551 = sqrt(log(((pert*params(55,1))^2)/(params(55,1)^2)+1));
params(55,1) = lognrnd(mu551,sigma551);
% 
params(56,1) = 1100; % Capture of TNF
mu561 = log((params(56,1)^2)/sqrt(((pert*params(56,1))^2)+(params(56,1)^2)));
sigma561 = sqrt(log(((pert*params(56,1))^2)/(params(56,1)^2)+1));
params(56,1) = lognrnd(mu561,sigma561);
params(56,2) = 0.001; % Scale for external (media) vs. internal (cellular) volumes
%
params(57,1) = 0.021; % Release of TNF
mu571 = log((params(57,1)^2)/sqrt(((pert*params(57,1))^2)+(params(57,1)^2)));
sigma571 = sqrt(log(((pert*params(57,1))^2)/(params(57,1)^2)+1));
params(57,1) = lognrnd(mu571,sigma571);
params(57,2) = 0.001; % Scale for external (media) vs. internal (cellular) volumes
%
params(58,1) = 0.125; % Internalization/degradation of complexed TNFR
mu581 = log((params(58,1)^2)/sqrt(((pert*params(58,1))^2)+(params(58,1)^2)));
sigma581 = sqrt(log(((pert*params(58,1))^2)/(params(58,1)^2)+1));
params(58,1) = lognrnd(mu581,sigma581);
%
params(59,1) = 34.08; % Association of TRAF2/RIP1 with receptor trimer
mu591 = log((params(59,1)^2)/sqrt(((pert*params(59,1))^2)+(params(59,1)^2)));
sigma591 = sqrt(log(((pert*params(59,1))^2)/(params(59,1)^2)+1));
params(59,1) = lognrnd(mu591,sigma591);
%
params(60,1) = 0.03812; % Dissociation of TRAF2/RIP1 with receptor trimer
mu601 = log((params(60,1)^2)/sqrt(((pert*params(60,1))^2)+(params(60,1)^2)));
sigma601 = sqrt(log(((pert*params(60,1))^2)/(params(60,1)^2)+1));
params(60,1) = lognrnd(mu601,sigma601);
%
params(61,1) = 0.125; % Internalization/degradation of complexed TNFR
mu611 = log((params(61,1)^2)/sqrt(((pert*params(61,1))^2)+(params(61,1)^2)));
sigma611 = sqrt(log(((pert*params(61,1))^2)/(params(61,1)^2)+1));
params(61,1) = lognrnd(mu611,sigma611);
%
params(62,1) = 1.875; % Activation of complexed TNFR
mu621 = log((params(62,1)^2)/sqrt(((pert*params(62,1))^2)+(params(62,1)^2)));
sigma621 = sqrt(log(((pert*params(62,1))^2)/(params(62,1)^2)+1));
params(62,1) = lognrnd(mu621,sigma621);
%
params(63,1) = 320.3; % Inactivation of complexed TNFR
mu631 = log((params(63,1)^2)/sqrt(((pert*params(63,1))^2)+(params(63,1)^2)));
sigma631 = sqrt(log(((pert*params(63,1))^2)/(params(63,1)^2)+1));
params(63,1) = lognrnd(mu631,sigma631);
%
params(64,1) = 0.125; % Internalization/degradation of complexed TNFR
mu641 = log((params(64,1)^2)/sqrt(((pert*params(64,1))^2)+(params(64,1)^2)));
sigma641 = sqrt(log(((pert*params(64,1))^2)/(params(64,1)^2)+1));
params(64,1) = lognrnd(mu641,sigma641);
%
params(65,1) = 1889; % Activation of TAK1 by C1
mu651 = log((params(65,1)^2)/sqrt(((pert*params(65,1))^2)+(params(65,1)^2)));
sigma651 = sqrt(log(((pert*params(65,1))^2)/(params(65,1)^2)+1));
params(65,1) = lognrnd(mu651,sigma651);
%
params(66,1) = 0.5188; % Inactivation of TAK1
mu661 = log((params(66,1)^2)/sqrt(((pert*params(66,1))^2)+(params(66,1)^2)));
sigma661 = sqrt(log(((pert*params(66,1))^2)/(params(66,1)^2)+1));
params(66,1) = lognrnd(mu661,sigma661);
%
params(67,1) = 18.79; % Activation of IKK by TAK1
mu671 = log((params(67,1)^2)/sqrt(((pert*params(67,1))^2)+(params(67,1)^2)));
sigma671 = sqrt(log(((pert*params(67,1))^2)/(params(67,1)^2)+1));
params(67,1) = lognrnd(mu671,sigma671);
params(67,2) = 2; % Hill coefficient for IKK activation
params(67,3) = 0.001116; % EC50 for mRNA syn
%
params(68,1) = 1e-06; % TLR1/2 synthesis
mu681 = log((params(68,1)^2)/sqrt(((pert*params(68,1))^2)+(params(68,1)^2)));
sigma681 = sqrt(log(((pert*params(68,1))^2)/(params(68,1)^2)+1));
params(68,1) = lognrnd(mu681,sigma681);
%
params(69,1) = 0.0004; % TLR1/2 degradation
mu691 = log((params(69,1)^2)/sqrt(((pert*params(69,1))^2)+(params(69,1)^2)));
sigma691 = sqrt(log(((pert*params(69,1))^2)/(params(69,1)^2)+1));
params(69,1) = lognrnd(mu691,sigma691);
%
params(70,1) = 1; % Association of CD14 and lipoprotein
mu701 = log((params(70,1)^2)/sqrt(((pert*params(70,1))^2)+(params(70,1)^2)));
sigma701 = sqrt(log(((pert*params(70,1))^2)/(params(70,1)^2)+1));
params(70,1) = lognrnd(mu701,sigma701);
params(70,2) = 0.001; % Scale for external (media) vs. internal (cellular) volumes
%
params(71,1) = 1.8; % Dissociation of CD14/lipoprotein
mu711 = log((params(71,1)^2)/sqrt(((pert*params(71,1))^2)+(params(71,1)^2)));
sigma711 = sqrt(log(((pert*params(71,1))^2)/(params(71,1)^2)+1));
params(71,1) = lognrnd(mu711,sigma711);
params(71,2) = 0.001; % Scale for external (media) vs. internal (cellular) volumes
%
params(72,1) = 5.543; % NaN
mu721 = log((params(72,1)^2)/sqrt(((pert*params(72,1))^2)+(params(72,1)^2)));
sigma721 = sqrt(log(((pert*params(72,1))^2)/(params(72,1)^2)+1));
params(72,1) = lognrnd(mu721,sigma721);
%
params(73,1) = 0.07; % Degradation of CD14-P3CSK
mu731 = log((params(73,1)^2)/sqrt(((pert*params(73,1))^2)+(params(73,1)^2)));
sigma731 = sqrt(log(((pert*params(73,1))^2)/(params(73,1)^2)+1));
params(73,1) = lognrnd(mu731,sigma731);
%
params(74,1) = 0.02; % NaN
mu741 = log((params(74,1)^2)/sqrt(((pert*params(74,1))^2)+(params(74,1)^2)));
sigma741 = sqrt(log(((pert*params(74,1))^2)/(params(74,1)^2)+1));
params(74,1) = lognrnd(mu741,sigma741);
%
params(75,1) = 0.001; % Degradation of ligand/receptor
mu751 = log((params(75,1)^2)/sqrt(((pert*params(75,1))^2)+(params(75,1)^2)));
sigma751 = sqrt(log(((pert*params(75,1))^2)/(params(75,1)^2)+1));
params(75,1) = lognrnd(mu751,sigma751);
%
params(76,1) = 150; % Activation of MyD88
mu761 = log((params(76,1)^2)/sqrt(((pert*params(76,1))^2)+(params(76,1)^2)));
sigma761 = sqrt(log(((pert*params(76,1))^2)/(params(76,1)^2)+1));
params(76,1) = lognrnd(mu761,sigma761);
params(76,2) = 3; % Hill coefficient for MyD88 activation
params(76,3) = 0.0032; % EC50 for MyD88 activation
%
params(77,1) = 3e-06; % TLR3 synthesis
mu771 = log((params(77,1)^2)/sqrt(((pert*params(77,1))^2)+(params(77,1)^2)));
sigma771 = sqrt(log(((pert*params(77,1))^2)/(params(77,1)^2)+1));
params(77,1) = lognrnd(mu771,sigma771);
%
params(78,1) = 0.0007; % TLR3 degradation
mu781 = log((params(78,1)^2)/sqrt(((pert*params(78,1))^2)+(params(78,1)^2)));
sigma781 = sqrt(log(((pert*params(78,1))^2)/(params(78,1)^2)+1));
params(78,1) = lognrnd(mu781,sigma781);
%
params(79,1) = 0.04; % Poly(I:C) internalization
mu791 = log((params(79,1)^2)/sqrt(((pert*params(79,1))^2)+(params(79,1)^2)));
sigma791 = sqrt(log(((pert*params(79,1))^2)/(params(79,1)^2)+1));
params(79,1) = lognrnd(mu791,sigma791);
params(79,2) = 0.03; % EC50 for poly(I:C) internalization
params(79,3) = 1; % Hill coefficient for poly(I:C) internalization
params(79,4) = 0.001; % NaN
%
params(80,1) = 0.04; % NaN
mu801 = log((params(80,1)^2)/sqrt(((pert*params(80,1))^2)+(params(80,1)^2)));
sigma801 = sqrt(log(((pert*params(80,1))^2)/(params(80,1)^2)+1));
params(80,1) = lognrnd(mu801,sigma801);
params(80,2) = 0.001; % Poly(I:C) release
%
params(81,1) = 0.5; % NaN
mu811 = log((params(81,1)^2)/sqrt(((pert*params(81,1))^2)+(params(81,1)^2)));
sigma811 = sqrt(log(((pert*params(81,1))^2)/(params(81,1)^2)+1));
params(81,1) = lognrnd(mu811,sigma811);
%
params(82,1) = 0.025; % NaN
mu821 = log((params(82,1)^2)/sqrt(((pert*params(82,1))^2)+(params(82,1)^2)));
sigma821 = sqrt(log(((pert*params(82,1))^2)/(params(82,1)^2)+1));
params(82,1) = lognrnd(mu821,sigma821);
%
params(83,1) = 0.0007; % Bound poly(I:C)-TLR3 degradation
mu831 = log((params(83,1)^2)/sqrt(((pert*params(83,1))^2)+(params(83,1)^2)));
sigma831 = sqrt(log(((pert*params(83,1))^2)/(params(83,1)^2)+1));
params(83,1) = lognrnd(mu831,sigma831);
% %
params(84,1) = 20; %  Activation of TRIF by bound TLR3
mu841 = log((params(84,1)^2)/sqrt(((pert*params(84,1))^2)+(params(84,1)^2)));
sigma841 = sqrt(log(((pert*params(84,1))^2)/(params(84,1)^2)+1));
params(84,1) = lognrnd(mu841,sigma841);
%
params(85,1) = 2e-06; % TLR9 synthesis
mu851 = log((params(85,1)^2)/sqrt(((pert*params(85,1))^2)+(params(85,1)^2)));
sigma851 = sqrt(log(((pert*params(85,1))^2)/(params(85,1)^2)+1));
params(85,1) = lognrnd(mu851,sigma851);
% %
params(86,1) = 0.0004; % TLR9 degradation
mu861 = log((params(86,1)^2)/sqrt(((pert*params(86,1))^2)+(params(86,1)^2)));
sigma861 = sqrt(log(((pert*params(86,1))^2)/(params(86,1)^2)+1));
params(86,1) = lognrnd(mu861,sigma861);
%
params(87,1) = 0.0004; % TLR9 degradation (N terminus fragment)
mu871 = log((params(87,1)^2)/sqrt(((pert*params(87,1))^2)+(params(87,1)^2)));
sigma871 = sqrt(log(((pert*params(87,1))^2)/(params(87,1)^2)+1));
params(87,1) = lognrnd(mu871,sigma871);
%
params(88,1) = 0.015; % CpG internalization
mu881 = log((params(88,1)^2)/sqrt(((pert*params(88,1))^2)+(params(88,1)^2)));
sigma881 = sqrt(log(((pert*params(88,1))^2)/(params(88,1)^2)+1));
params(88,1) = lognrnd(mu881,sigma881);
params(88,2) = 0.5; % EC50 for CpG internalization
params(88,3) = 1; % Hill coefficient for CpG internalization
params(88,4) = 0.001; % NaN
%
params(89,1) = 0.028; % CpG exchange from endosome
mu891 = log((params(89,1)^2)/sqrt(((pert*params(89,1))^2)+(params(89,1)^2)));
sigma891 = sqrt(log(((pert*params(89,1))^2)/(params(89,1)^2)+1));
params(89,1) = lognrnd(mu891,sigma891);
params(89,2) = 0.001; % NaN
%
params(90,1) = 3; % Ligand-receptor association
mu901 = log((params(90,1)^2)/sqrt(((pert*params(90,1))^2)+(params(90,1)^2)));
sigma901 = sqrt(log(((pert*params(90,1))^2)/(params(90,1)^2)+1));
params(90,1) = lognrnd(mu901,sigma901);
%
params(91,1) = 0.5; % Ligand-receptor dissociation
mu911 = log((params(91,1)^2)/sqrt(((pert*params(91,1))^2)+(params(91,1)^2)));
sigma911 = sqrt(log(((pert*params(91,1))^2)/(params(91,1)^2)+1));
params(91,1) = lognrnd(mu911,sigma911);
%
params(92,1) = 3; % Mediated degrdadation of bound TLR9
mu921 = log((params(92,1)^2)/sqrt(((pert*params(92,1))^2)+(params(92,1)^2)));
sigma921 = sqrt(log(((pert*params(92,1))^2)/(params(92,1)^2)+1));
params(92,1) = lognrnd(mu921,sigma921);
%
params(93,1) = 0.0016; % Bound CpG-TLR9 degradation
mu931 = log((params(93,1)^2)/sqrt(((pert*params(93,1))^2)+(params(93,1)^2)));
sigma931 = sqrt(log(((pert*params(93,1))^2)/(params(93,1)^2)+1));
params(93,1) = lognrnd(mu931,sigma931);
%
params(94,1) = 200; % Activation of MyD88
mu941 = log((params(94,1)^2)/sqrt(((pert*params(94,1))^2)+(params(94,1)^2)));
sigma941 = sqrt(log(((pert*params(94,1))^2)/(params(94,1)^2)+1));
params(94,1) = lognrnd(mu941,sigma941);
params(94,2) = 3; % Hill coefficient for MyD88 activation
params(94,3) = 0.0032; % EC50 for MyD88 activation
%
params(95,1) = 0; % degradation of NF-kB (used as proxy for irreversible sequestration)


% SPECIES
species.NAMES = {...
'stim' ...1
'IkBa' ...2
'IkBan' ...3
'IkBaNFkB' ...4
'IkBaNFkBn' ...5
'IkBat' ...6
'IKKIkBaNFkB' ...7
'IKKIkBa' ...8
'NFkB' ...9
'NFkBn' ...10
'IKK_off' ...11
'IKK' ...12
'IKK_i' ...13
'LPS' ...14
'CD14' ...15
'CD14LPS' ...16
'CD14LPSen' ...17
'TLR4' ...18
'TLR4en' ...19
'TLR4LPS' ...20
'TLR4LPSen' ...21
'MyD88_off' ...22
'MyD88' ...23
'TRIF_off' ...24
'TRIF' ...25
'TRAF6_off' ...26
'TRAF6' ...27
'TNF' ...28
'TNFR' ...29
'TNFR_TNF' ...30
'TTR' ...31
'C1_off' ...32
'C1' ...33
'TAK1_off' ...34
'TAK1' ...35
'Pam3CSK' ...36
'TLR2' ...37
'CD14_P3CSK' ...38
'TLR2_P3CSK' ...39
'polyIC' ...40
'polyIC_en' ...41
'TLR3' ...42
'TLR3_polyIC' ...43
'CpG' ...44
'CpG_en' ...45
'TLR9' ...46
'TLR9_CpG' ...47
'TLR9_N' ...48
};